apiVersion: v1
kind: Service
metadata:
  labels:
    app: messages
  name: messages
spec:
  ports:
  - name: "http"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: messages
  type: NodePort

